# Madlibs is a word game where you can create a story by filling the blanks with random words
print("Today I went to a ____ zoo.")
print("In an exhibit, I saw a ____ .")
print(" ____ was ____ and ____ ")
print("I was ____ !")
adj1 = input("Enter adjective (discription) : ")
noun1 = input("Enter a noun (person, place, thing): ")
adj2 = input("Enter adjective (discription) : ")
verb1 = input("Enter a verb ending with 'ing' : ")
adj3 = input("Enter adjective (discription) : ")
print(f"Today I went to a {adj1} zoo.")
print(f"In an exhibit, I saw a {noun1}.")
print(f"{noun1} was {adj2} and {verb1}")
print(f"I was {adj3}!")